# --- Frontend Dockerfile ---
    FROM node:16-alpine AS build

    WORKDIR /usr/src/app
    
    # Copy package and install
    COPY package.json .
    RUN npm install
    
    # Copy source & build
    COPY public ./public
    COPY src ./src
    RUN npm run build
    
    # Serve via nginx
    FROM nginx:stable-alpine
    COPY --from=build /usr/src/app/build /usr/share/nginx/html
    EXPOSE 80
    CMD ["nginx", "-g", "daemon off;"]
    